### ISSUE TITLE
访问API超时，但是没有显示问题

### ISSUE THREAD

**Issue by ABKQPO** [zhaomaoniu/nonebot-plugin-gemini#1]
测试可以正常访问谷歌等相关网站，插件返回只有RetryError: Timeout of 60.0s exceeded while calling target function, last exception:

**Comment by XibieTime** [comment]
遇到了同样的问题

**Comment by zhaomaoniu** [comment]
由于google.generativeai的限制，插件暂时没有使用代理
之后可能会以 patch该库 或 转用rest api 的方式支持代理
目前只能在可以直接访问谷歌的网络环境下正常使用该插件

**Comment by ABKQPO** [comment]
如果使用全局代理呢

**Comment by zhaomaoniu** [comment]
如果你的终端被代理了，也可以正常使用

**Comment by zhaomaoniu** [comment]
已支持配置代理，请更新本插件后按照 README 修改配置后再次运行尝试
