### ISSUE TITLE
求帮助：geminichat连续对话是不是不能识别图片呢

### ISSUE THREAD

**Issue by VAHua** [zhaomaoniu/nonebot-plugin-gemini#2]
使用指令gemini：
![image](https://github.com/zhaomaoniu/nonebot-plugin-gemini/assets/129832780/6cc57173-a90a-4d94-995a-122c5e5c1266)

使用指令geminichat
![image](https://github.com/zhaomaoniu/nonebot-plugin-gemini/assets/129832780/42b9cb92-2676-40c6-b76e-7b692338b1f9)

**Comment by zhaomaoniu** [comment]
由于API的限制，连续对话只能使用模型 Gemini-Pro，无法识别图片

**Comment by zhaomaoniu** [comment]
> The gemini-pro-vision model (for text-and-image input) is not yet optimized for multi-turn conversations. Make sure to use gemini-pro and text-only input for chat use cases.
[Quickstart: Get started with Gemini using REST API](https://ai.google.dev/tutorials/rest_quickstart)
