### ISSUE TITLE
我可以在此插件的基础上二次开发吗？

### ISSUE THREAD

**Issue by MoonofBridge24** [zhaomaoniu/nonebot-plugin-gemini#3]
由于nb商店里没有符合我需求的插件，所以我前段时间基于您的插件私下进行了魔改，重写了init.py中的大部分代码，增加了预设以及白名单的增删查改功能，实现了群聊中随机响应，现在我想发布在nb商店中，不知道您对此是否介意？

**Comment by zhaomaoniu** [comment]
不介意。麻烦在使用我的代码的地方进行标注
