### ISSUE TITLE
proxy代理

### ISSUE THREAD

**Issue by yuankong-H** [zhaomaoniu/nonebot-plugin-gemini#5]
你的proxy是怎么弄的，我安装了之后，我的其它插件访问本地的fastapi全寄了？

**Comment by yuankong-H** [comment]
改好了，竟然是全局代理，我排查了半天原来是你的插件搞的

**Comment by zhaomaoniu** [comment]
碍于 google-generativeai 所依赖的 gRPC 没有提供足够的代理配置方法，不被 Gemini API 支持的国家或地区只有通过配置环境变量的方式才能配置代理。

关于你提及的「其它插件访问本地的fastapi全寄了」的问题，可以通过下列方式解决：
- (推荐) 在你使用的代理服务中添加规则，使内网访问不通过代理
- 安装本插件的 0.3.0 版本。由于该版本基于 Gemini REST API 进行请求，并不受限于 gRPC 的代理方式，所以不会产生内网不能访问的问题
