### ISSUE TITLE
希望增加黑名单功能

### ISSUE THREAD

**Issue by ZihuaGaoCHN** [zhaomaoniu/nonebot-plugin-gemini#6]
如题，希望增加群黑名单或者个人黑名单功能，通过编辑env文件设置，以免被该群成员或该用户使用。

**Comment by zhaomaoniu** [comment]
已在 [v0.5.1](https://github.com/zhaomaoniu/nonebot-plugin-gemini/releases/tag/v0.5.1) 中添加此功能，可根据 README 中 [配置](https://github.com/zhaomaoniu/nonebot-plugin-gemini#%E9%85%8D%E7%BD%AE) 一栏进行配置
